# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Arendelle	
tagline:          Simple forward thinking sketching language
url:              http://arendelle.github.io
paginate:         1
baseurl:          /
author:
  name:           Pouya Kary and Micha Hanslemann
  url:            https://arendelle.org/crew
  email:          hey@arendelle.org

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/arendelle/arendelle.github.io
